# Generated by Django 4.1.7 on 2023-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='note',
            field=models.CharField(blank=True, max_length=30, verbose_name='Текстовая заметка'),
        ),
    ]
